# Generated by Django 5.1.5 on 2025-01-20 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='base/advantage/icon/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Avantaj',
                'verbose_name_plural': 'Avantajlar',
            },
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=128)),
                ('paragraph', models.TextField()),
            ],
            options={
                'verbose_name': 'Doktor bilgileri',
                'verbose_name_plural': 'Doktor bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='base/service/icon/')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='base/slide/image/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Stayt',
                'verbose_name_plural': 'Slaytlar',
            },
        ),
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('pinterest', models.URLField()),
            ],
            options={
                'verbose_name': 'Sosyal medya hesapları',
                'verbose_name_plural': 'Sosyal medya hesapları',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='base/portfolio/image/')),
                ('title', models.CharField(max_length=128)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service')),
            ],
            options={
                'verbose_name': 'Portfoyo',
                'verbose_name_plural': 'Portfoyo',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service')),
            ],
            options={
                'verbose_name': 'Hizmet fiyatı',
                'verbose_name_plural': 'Hizmet fiyatları',
            },
        ),
        migrations.CreateModel(
            name='ServicePriceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_included', models.BooleanField(default=True)),
                ('service_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.serviceprice')),
            ],
            options={
                'verbose_name': 'Hizmet fiyatı özelliği',
                'verbose_name_plural': 'Hizmet fiyatı özellikleri',
            },
        ),
    ]
