# Generated by Django 5.1.5 on 2025-01-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='type',
            field=models.CharField(choices=[('1', 'FIRST'), ('2', 'SECOND'), ('3', 'THIRD')], default='1', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.ImageField(upload_to='base/advantage/icon/', verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='area',
            field=models.CharField(max_length=128, verbose_name='Uzmanlık alanı'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Adı soyadı'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='paragraph',
            field=models.TextField(verbose_name='Kısa paragraf'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='base/portfolio/image/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service', verbose_name='Hizmet'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='base/service/icon/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service', verbose_name='Hizmet'),
        ),
        migrations.AlterField(
            model_name='servicepricevalue',
            name='is_included',
            field=models.BooleanField(default=True, verbose_name='Dahilmidir?'),
        ),
        migrations.AlterField(
            model_name='servicepricevalue',
            name='service_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.serviceprice', verbose_name='Hizmet fiyatı'),
        ),
        migrations.AlterField(
            model_name='servicepricevalue',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='base/slide/image/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='socialaccounts',
            name='facebook',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='socialaccounts',
            name='instagram',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='socialaccounts',
            name='pinterest',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
