# Generated by Django 5.1.5 on 2025-01-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_slide_link_slide_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='base/service-category/image', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Hizmet kategorileri',
            },
        ),
        migrations.RemoveField(
            model_name='serviceprice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicepricevalue',
            name='service_price',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Fiyat (USD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.servicecategory'),
        ),
        migrations.DeleteModel(
            name='ServicePrice',
        ),
        migrations.DeleteModel(
            name='ServicePriceValue',
        ),
    ]
