# Generated by Django 5.1.5 on 2025-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_socialaccount_delete_socialaccounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.TextField(verbose_name='SVG kodu'),
        ),
    ]
