# Generated by Django 5.1.5 on 2025-01-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_socialaccount_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=128, verbose_name='Telefon numarası')),
                ('phone_number_repr', models.CharField(max_length=128, verbose_name='Telefon numarası')),
                ('phone_number_wa', models.CharField(max_length=128, verbose_name='Whatsapp numarası')),
                ('phone_number_wa_repr', models.CharField(max_length=128, verbose_name='Whatsapp numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta adresi')),
                ('address', models.TextField(verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'İletişim bilgileri',
            },
        ),
    ]
