# Generated by Django 5.1.5 on 2025-01-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_contactinfo_options_contactinfo_address_gm_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address_gm_src',
            field=models.TextField(verbose_name='Google harita iframe linki'),
        ),
    ]
