# Generated by Django 5.1.5 on 2025-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_contactinfo_address_gm_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='logo',
            field=models.ImageField(default='', upload_to='base/doctor-info/logo/', verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='slogan',
            field=models.TextField(default='', verbose_name='Slogan'),
            preserve_default=False,
        ),
    ]
