# Generated by Django 5.1.5 on 2025-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_doctorinfo_logo_doctorinfo_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
            ],
            options={
                'verbose_name': 'Sıkça sorulan soru',
                'verbose_name_plural': 'Sıkça sorulan sorular',
            },
        ),
    ]
