# Generated by Django 5.1.5 on 2025-01-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_gallerycategory_galleryimage_delete_advantage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name': 'Galeri kategorisi', 'verbose_name_plural': 'Galeri kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Galeri resmi', 'verbose_name_plural': 'Galeri resimleri'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.gallerycategory'),
        ),
    ]
