# Generated by Django 5.1.5 on 2025-01-30 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_gallerycategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='base/video-review/image/', verbose_name='Resim')),
                ('youtube_url', models.URLField(verbose_name='Youtube linki')),
            ],
            options={
                'verbose_name': 'Video değerlendirmesi',
                'verbose_name_plural': 'Video değerlendirmeleri',
            },
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='base.gallerycategory'),
        ),
    ]
