# Generated by Django 5.1.5 on 2025-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_videoreview_alter_galleryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_tr',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
