# Generated by Django 5.1.5 on 2025-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_service_title_en_service_title_ru_service_title_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
    ]
