# Generated by Django 5.1.5 on 2025-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_faq_answer_en_faq_answer_ru_faq_answer_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='area_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Uzmanlık alanı'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='area_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Uzmanlık alanı'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='area_tr',
            field=models.CharField(max_length=128, null=True, verbose_name='Uzmanlık alanı'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Adı soyadı'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='full_name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Adı soyadı'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='full_name_tr',
            field=models.CharField(max_length=128, null=True, verbose_name='Adı soyadı'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='logo_en',
            field=models.ImageField(null=True, upload_to='base/doctor-info/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='logo_ru',
            field=models.ImageField(null=True, upload_to='base/doctor-info/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='logo_tr',
            field=models.ImageField(null=True, upload_to='base/doctor-info/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='paragraph_en',
            field=models.TextField(null=True, verbose_name='Kısa paragraf'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='paragraph_ru',
            field=models.TextField(null=True, verbose_name='Kısa paragraf'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='paragraph_tr',
            field=models.TextField(null=True, verbose_name='Kısa paragraf'),
        ),
    ]
