# Generated by Django 5.1.5 on 2025-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_doctorinfo_area_en_doctorinfo_area_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='title_tr',
            field=models.CharField(max_length=128, null=True, verbose_name='Başlık'),
        ),
    ]
